# Generated by Django 5.2.4 on 2025-10-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="add",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("branch_name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="product_image/")),
                ("descriptions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="add_mechanics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_mechanic", models.CharField(max_length=100)),
                ("contact_mechanic", models.CharField(max_length=50)),
                ("email_mechanic", models.EmailField(max_length=254)),
                ("specialization_mechanic", models.TextField()),
                ("location_mechanic", models.CharField(max_length=100)),
                ("available_from_mechanic", models.CharField(max_length=100)),
                ("available_to_mechanic", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="add_service_center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_service", models.CharField(max_length=100)),
                ("email_service", models.EmailField(max_length=254)),
                ("branch_name_service", models.CharField(max_length=100)),
                ("contact_service", models.CharField(max_length=100)),
                ("location_service", models.CharField(max_length=100)),
                ("image_service", models.ImageField(upload_to="product_image/")),
                ("descriptions_service", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_booking", models.CharField(max_length=100)),
                ("email_booking", models.EmailField(max_length=254)),
                ("number_booking", models.CharField(max_length=50)),
                ("vehicle_number", models.CharField(max_length=100)),
                ("service_date", models.CharField(max_length=100)),
                ("notes_booking", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "OK"), ("pending", "Pending")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ev.add_service_center",
                    ),
                ),
            ],
        ),
    ]
