# Generated by Django 5.2.4 on 2025-10-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ev", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_contact", models.CharField(max_length=100)),
                ("email_contact", models.EmailField(max_length=254)),
                ("message_contact", models.TextField()),
            ],
        ),
    ]
